# Generated by Django 4.1 on 2023-08-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='faiz.com', upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
